// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzOJRR_dNbL-P75JNHy9MURC_ju4amkk',
    appId: '1:920954165272:web:f6ad54e80a7c5d0bab4b6d',
    messagingSenderId: '920954165272',
    projectId: 'chjoo-firebase-flutter-001',
    authDomain: 'chjoo-firebase-flutter-001.firebaseapp.com',
    storageBucket: 'chjoo-firebase-flutter-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vShi9n3DWt540SvzwogQ3YXDsI6AKJw',
    appId: '1:920954165272:android:5190840bfd0e55aaab4b6d',
    messagingSenderId: '920954165272',
    projectId: 'chjoo-firebase-flutter-001',
    storageBucket: 'chjoo-firebase-flutter-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtlhXSxUZ43QSBv84vXFs_FDSQ26-bSI',
    appId: '1:920954165272:ios:28e4d64f0145b972ab4b6d',
    messagingSenderId: '920954165272',
    projectId: 'chjoo-firebase-flutter-001',
    storageBucket: 'chjoo-firebase-flutter-001.appspot.com',
    iosClientId: '920954165272-p5k107lccrl3d8l3666t6ijuv6im7h7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtlhXSxUZ43QSBv84vXFs_FDSQ26-bSI',
    appId: '1:920954165272:ios:28e4d64f0145b972ab4b6d',
    messagingSenderId: '920954165272',
    projectId: 'chjoo-firebase-flutter-001',
    storageBucket: 'chjoo-firebase-flutter-001.appspot.com',
    iosClientId: '920954165272-p5k107lccrl3d8l3666t6ijuv6im7h7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
